# Generated by Django 6.0.3 on 2026-04-04 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_artisan_delete_review_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artisan')),
            ],
        ),
    ]
