# Generated by Django 6.0.3 on 2026-04-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_review_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artisans/'),
        ),
    ]
