# Generated by Django 6.0.3 on 2026-04-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_artisan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
