# Generated by Django 6.0.3 on 2026-04-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_artisan_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artisan',
            old_name='approved',
            new_name='is_approved',
        ),
        migrations.AddField(
            model_name='artisan',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
