# Generated by Django 6.0.3 on 2026-04-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_approved_artisan_is_approved_artisan_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
