# Generated by Django 6.0.3 on 2026-04-30 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_artisan_is_approved_alter_artisan_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='message',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='sender_type',
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='artisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artisan'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
